
skinparam classAttributeIconSize 0


abstract Agent {
    + name: str
    + asset: Asset 
    + bidding_strategy: BiddingStrategy 
    + forecasts: Forecasts
    + __init__()
    + get_latest_forecasts()
    + get_device_schedule()
    + get_asset_state()
    + generate_market_signal()
    + send_asset_control()
    + record_metrics()
}
abstract Asset { 
    + asset_name: str 
    + asset_model: AssetModel 
    + asset_state: AssetState 
    + metrics: Metrics 

    + AssetState simulate_asset_operation()
    + void get_asset_state()
    + void send_asset_control_signal() 
} 
abstract AssetState { 
    + asset_state_variables: var 
} 
abstract AssetModel { 
    + asset_model_parameters: var 
} 
abstract BiddingStrategy {
    + asset: Asset 
    + amenity_bid: AuctionBid
    + commodity_bid: AuctionBid 

    + void form_amentity_bid()
    + void coverty_amenity_to_commodity()
}
abstract Bid {   
}
abstract MarketInterface {
    + market_state: MarketStateMachine 

    + void send_market_signal()
    + void get_market_signa()

}
abstract Forecasts{

}
abstract MarketStateMachine {
}
abstract Metrics {
    + update_data()
    + write_out_data()

}
abstract HVACAsset {
}
abstract HVACAssetState {
    + update_asset_state()
}
abstract HVACAssetModel {
    simulate_time_step(time_step_size: DateTime)
}
abstract DoubleAuctionMarketInterface {
    + void send_bid()
    + void get_clearing_price()
}
abstract DoubleAuctionMarketStateMachine {
}
abstract DSOTAgent {
}
abstract DSOTBiddingStrategy{
    + solver: SolverEnum
}


Agent "1" *-- "1" Asset 
Agent "1" *-- "1" Metrics
Agent "1" *-- "1" Forecasts
Agent "1" *-- "1" BiddingStrategy
BiddingStrategy "1" *-- "1" MarketInterface 
Asset "1" *-- "1" AssetState 
Asset "1" *-- "1" AssetModel 
MarketInterface "1" *-- "1" MarketStateMachine


Bid  <|--  AuctionBid 
DoubleAuctionMarketInterface  --|>  MarketInterface
DSOTRTMarketInterface  --|>  DoubleAuctionMarketInterface
DSOTDAMarketInterface  --|>  DoubleAuctionMarketInterface
Agent  <|--  DSOTAgent
DSOTAgent  <|--  HVACDSOTAgent
Asset  <|--  HVACAsset
HVACAsset  <|--  HVACDSOTAsset
AssetModel  <|--  HVACAssetModel
HVACAssetModel  <|--  HVACDSOTAssetModel
AssetState  <|--  HVACAssetState
HVACAssetState  <|--  HVACDSOTAssetState
DSOTBiddingStrategy  <|--  HVACDSOTRTBiddingStrategy
DSOTBiddingStrategy  <|--  HVACDSOTDABiddingStrategy
BiddingStrategy <|-- DSOTBiddingStrategy
AuctionBid  <|--  DSOT4pointBid
MarketStateMachine  <|--  DoubleAuctionMarketStateMachine
DoubleAuctionMarketStateMachine  <|--  DSOTRTMarketStateMachine
DoubleAuctionMarketStateMachine  <|--  DSOTDAMarketStateMachine